name: Sync Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone Wiki repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          rm -rf wiki-repo
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.wiki.git wiki-repo

      - name: Sync files into Wiki repo
        run: |
          rsync -av --delete wiki/ wiki-repo/

      - name: Commit and push changes
        working-directory: wiki-repo
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore(wiki): sync from repo wiki directory"
            git push origin HEAD:master || git push origin HEAD:main || git push
          else
            echo "No changes to sync."
          fi
